### ISSUE TITLE
Question text of radioButtonsWithAnswer does not get translated

### ISSUE THREAD

**Issue by masarapmabuhay** [chrisamanse/UsbongKit#11]
Salut! I found that the question text (not the options) of the `radioButtonsWithAnswer` node does not get translated even if there is a translation available in the trans folder.

<img width="375" alt="screen shot 2016-10-27 at 8 56 49 am" src="https://cloud.githubusercontent.com/assets/344066/19750425/8a9ae804-9c23-11e6-8fcd-43b5528e6411.png">

```
    <task-node name="radioButtonsWithAnswer~@audioName=question1~1. What is いちじはん (ichijihan)?Answer=1">
        <task name="A) 11:00"></task>
        <task name="B) 1:30"></task>
        <task name="C) 3:00"></task>
        <task name="C) 4:30"></task>
        <transition to="imageTextDisplay~correct~@audioName=correct~1~Correct!{br}The correct answer is: B) 1:30" name="Yes"></transition>
        <transition to="imageTextDisplay~incorrect~@audioName=incorrect~1~Incorrect!{br}The correct answer is: B) 1:30" name="No"></transition> 
    </task-node>
```

Merci beaucoup!

**Comment by masarapmabuhay** [comment]
Bonnes nouvelles! Good news! I was able to fix this issue! I added `translateText(parseText(...))`in `// Rejoin.`

<img width="377" alt="screen shot 2016-10-27 at 9 21 38 am" src="https://cloud.githubusercontent.com/assets/344066/19750839/47335a2a-9c27-11e6-9722-40acfabec4b6.png">

```
                case .RadioButtonsWithAnswer:
                    let separator = "Answer="
                    var components = finalText.componentsSeparatedByString(separator)

                    // Get answer
                    if components.count > 1 {
                        currentTargetSelectedIndex = Int(components.removeLast())
                    }

                    // Rejoin
                    let text: String = translateText(parseText(components.joinWithSeparator(separator)))

                    // Create RadioButtons
                    node = RadioButtonsNode(text: text, options: tasks)
```

May I ask how I can send a pull request to merge our code via Xcode? I use `SourceTree` for UsbongKit (Android).

Merci bien!

**Comment by chrisamanse** [comment]
https://github.com/usbong/UsbongKit/issues/12#issuecomment-256529663

**Comment by masarapmabuhay** [comment]
Salut! I have merged the fix to UsbongKit (iOS)-`master`! I used `SourceTree`. Merci bien!
