### ISSUE TITLE
textFieldWithAnswer does not get translated

### ISSUE THREAD

**Issue by masarapmabuhay** [chrisamanse/UsbongKit#12]
Salut! I noticed that `textFieldWithAnswer` does not get translated even if there is a translation available in the trans folder.

<img width="378" alt="screen shot 2016-10-27 at 9 05 02 am" src="https://cloud.githubusercontent.com/assets/344066/19750539/870a960c-9c24-11e6-86e7-398b38b7330a.png">

```
 <task-node name="textFieldWithAnswer~@audioName=question3~3. How do you read these kanji characters (紙, 髪, 神)?Answer=kami|Kami|かみ|カミ">
        <transition to="imageTextDisplay~correct~@audioName=correct~Correct!{br}Yes, the correct answer is: かみ, カミ, kami." name="Yes"></transition>
        <transition to="imageTextDisplay~incorrect~@audioName=incorrect~3~Incorrect!{br}The correct answer is: かみ, カミ, kami." name="No"></transition>   
    </task-node>    
```

Merci beaucoup!

**Comment by masarapmabuhay** [comment]
Bonnes nouvelles! Good news! I was able to fix this issue. I added `translateText(parseText(...))` in `// Rejoin`.

<img width="377" alt="screen shot 2016-10-27 at 9 32 39 am" src="https://cloud.githubusercontent.com/assets/344066/19750977/6192f172-9c28-11e6-8a30-0cb46e1acfd7.png">

```
 case .TextFieldWithAnswer, .TextAreaWithAnswer:
                let separator = "Answer="
                var components = finalText.componentsSeparatedByString(separator)

                // Get answer
                if components.count > 1 {
                    currentTargetTextInput = components.removeLast()
                }

                // Rejoin
                let text: String = translateText(parseText(components.joinWithSeparator(separator)))

                // Create TextField or TextArea depending on taskNodeType
                node = (taskNodeType == .TextFieldWithAnswer) ? TextFieldNode(text: text) : TextAreaNode(text: text)

```

How do I then send a pull request to merge our code via Xcode?

Merci beaucoup!

**Comment by chrisamanse** [comment]
If you open UsbongKit with SourceTree, you can create a new branch then commit your changes. After committing the necessary changes, you can now push this branch to this GitHub repo. Now that your branch is visible in GitHub, you can create a pull request from that branch.

**Comment by masarapmabuhay** [comment]
Salut! Merci beaucoup pour ta réponse! D'accord! How about if I want to use Xcode to commit changes and create a pull request like what you do?

**Comment by chrisamanse** [comment]
I use the Terminal for git operations, and GitHub for GitHub operations (pull requests, issues, etc.).

It is possible to use Xcode for git operations. The operations can be found in _Source Control_ in the menu bar of Xcode (it contains commit, push, pull, discard changes, etc.).

**Comment by chrisamanse** [comment]
I use the Terminal for git operations, and GitHub for GitHub operations (pull requests, issues, etc.).

It is possible to use Xcode for git operations. The operations can be found in _Source Control_ in the menu bar (contains commit, push, pull, discard changes, etc.).

**Comment by masarapmabuhay** [comment]
Salut! Merci beaucoup pour ton conseil! Unfortunately, while I was testing Xcode to do git operations, I messed up: my code reverted back to an earlier version. It seems that the UsbongKit in the LIKHA-Guide is not updated. I'm now redoing most, but not all, of the steps again. Toutefois, je ferais de mon mieux! Merci!

**Comment by masarapmabuhay** [comment]
Salut! I have committed the updates to UsbongKit (iOS)-`master branch`. I went with using _SourceTree_, instead of _Xcode_ or _Terminal._ I also merged your `translate-tasks` branch to `master.` Shall I also merge your `disable-sleep` branch to `master`?
