### ISSUE TITLE
textFieldWithAnswer accepts any answer to be correct

### ISSUE THREAD

**Issue by masarapmabuhay** [chrisamanse/UsbongKit#13]
Salut! I noticed that `textFieldWithAnswer` accepts as `correct`even `wrong` answers. This is regardless of whether the language set is English or Filipino.

<img width="378" alt="screen shot 2016-10-27 at 9 05 02 am" src="https://cloud.githubusercontent.com/assets/344066/19751238/65b2c5b4-9c2a-11e6-8205-05b6367feec4.png">

Could it be related to the fix you did with regard to the use of the pipe, i.e. `|` for multiple answers?

Merci beaucoup toujours!

**Comment by chrisamanse** [comment]
May I know the XML for this current task node? In the example utree, it seems to be working fine.

**Comment by masarapmabuhay** [comment]
Salut! Here is the XML for this task node:

```
<task-node name="textFieldWithAnswer~@audioName=question3~3. How do you read these kanji characters (紙, 髪, 神)?Answer=kami|Kami|かみ|カミ">
        <transition to="imageTextDisplay~correct~@audioName=correct~3~Correct!{br}Yes, the correct answer is: かみ, カミ, kami." name="Yes"></transition>
        <transition to="imageTextDisplay~incorrect~@audioName=incorrect~3~Incorrect!{br}The correct answer is: かみ, カミ, kami." name="No"></transition>       
</task-node>    
```

Merci beaucoup!

**Comment by chrisamanse** [comment]
I tested this task node in the UsbongKit-example app, and the "Yes" and "No" transitions as expected. Are you using the latest version of UsbongKit?

**Comment by masarapmabuhay** [comment]
Salut! Merci beaucoup pour ta réponse! I am using the one from the LIKHA-Guide. I downloaded the file on Oct. 1, 2016. Perhaps, this version that I'm using isn't synced with the latest version of UsbongKit (iOS)? Cordialement!

**Comment by masarapmabuhay** [comment]
C'est vrai! I was not using the updated version of UsbongKit. I have merged your `translate-tasks`branch to `master`. `textFieldWithAnswer` now works, i.e. transitions to either "Yes" or "No". All is well. Merci beaucoup!
