### ISSUE TITLE
If text is scrolled down in one screen, the next screen would have the text also scrolled down

### ISSUE THREAD

**Issue by masarapmabuhay** [chrisamanse/UsbongKit#15]
Salut! I noticed that if I scrolled down the text in one screen, the next screen would have the text also scrolled down, thereby not showing the top image completely. I think this is related to: https://github.com/usbong/Usbong-iOS/issues/2 Merci beaucoup!

**Comment by chrisamanse** [comment]
Can you test the [scroll-top branch](https://github.com/usbong/UsbongKit/tree/scroll-top)?

**Comment by masarapmabuhay** [comment]
Salut! Oui, your fix resolved the issue. Merci beaucoup!

**Comment by masarapmabuhay** [comment]
Salut! Pardon, it seems that if the 1st screen is scrolled down to the bottom, and the 2nd screen has such a long text that it is also scrollable, when the person presses "Next", the 2nd screen will be automatically scrolled down to the bottom, thereby not showing the top image completely, if at all. Merci beaucoup!

**Comment by chrisamanse** [comment]
Hi @masarapmabuhay, I updated the scroll-top branch, and created the PR #20. Feel free to merge it to master once it works for you.
