### ISSUE TITLE
When "open quotation" is used, the word immediately right after it does not show the Word Hint 

### ISSUE THREAD

**Issue by masarapmabuhay** [chrisamanse/UsbongKit#17]
Salut! I noticed that when "open quotation" is used, the word immediately right after it does not show the Word Hint. 

![wordhintbug](https://cloud.githubusercontent.com/assets/344066/20174574/79e319a8-a779-11e6-916a-87756387c1ae.png)

Merci beaucoup!

**Comment by chrisamanse** [comment]
Found the code that causes this issue. It is caused by the String parsing that checks if a substring is a word: https://github.com/usbong/UsbongKit/blob/master/UsbongKit/Views/HintsTextView.swift#L103

``` swift
// Previous character should be whitespace or newline
let whitespaceAndNewLineCharacterSet = NSCharacterSet.whitespaceAndNewlineCharacterSet()
if range.location > 0 {
    let previousCharacterString = string.substringWithRange(NSRange(location: range.location - 1, length: 1))
    if previousCharacterString.rangeOfCharacterFromSet(whitespaceAndNewLineCharacterSet) == nil {
        foundStringIsWord = false
    }
}
```

To fix this, instead of just checking if the previous character is a whitespace or newline, it should also consider `"`.

**Comment by chrisamanse** [comment]
Let me know if 0addc21 fixes you're issue.

**Comment by chrisamanse** [comment]
Hi @masarapmabuhay, I updated the code and created PR #19. For a word to be considered a "word" by the parser, the previous character of the word can be any punctuation in general as defined in the Punctuation general category of [Unicode character property](https://en.wikipedia.org/wiki/Unicode_character_property#General_Category). Previously, it was set only to whitespace, thus, in `"Hindi ` was not considered a word previously.

**Comment by chrisamanse** [comment]
Feel free to merge it to `master` once you tested it.
